name: "Nix Build"
on: [push, pull_request]
jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build
    - run: nix flake check